### ISSUE TITLE
oserror with spaceKLIP.sk_style

### ISSUE THREAD

**Issue by wbalmer** [spacetelescope/spaceKLIP#172]
I have spaceklip installed via pip dev mode (pip install -e .). I keep getting this error whenever the style file is invoked.

```
OSError: 'spaceKLIP.sk_style' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
```

Not sure if this is a path issue on my end or something weird happening with my matplotlib install, or a bug others have encountered.  As someone who prefers to define my own style using my personal style file, I also just take issue with this being baked into spaceklip, because I have to comment/uncomment it out whenever I pull or push stuff.

**Comment by JarronL** [comment]
I think you need matplotlib >=3.7.1 for style files to load correctly from packages. 

You can test by doing one of these:

``` python
# To use: 
plt.style.use('spaceKLIP.sk_style')`

# Or
with plt.style.context('spaceKLIP.sk_style'):
    some_plot_function1()
    some_plot_function2()
    some_plot_function3()

# This also works:
@plt.style.context('spaceKLIP.sk_style')
def plotting_function(*args, **kwargs):
    plt.plot(*args, **kwargs)
```

So, the spaceKLIP style file shouldn't be modifying anything outside of this package, but most of the internal functions utilize the `with plt.style.context('spaceKLIP.sk_style'):` that makes it unavoidable for the internal functions at the moment.

I agree that we can probably think of a better way of implementing (or not) the spaceKLIP plotting style. The history is that before such style files existed, I had integrated something into pynrc for myself (before it was publicly available), which then translated over to webbpsf_ext [the original sin]. As a dependency to spaceKLIP, some of those settings got edited due to how different platforms would visualize text, etc., and then the whole implementation received pushback because it was hardcoded to modify a number of matplotlib settings, which was problematic for any subsequently loaded packages. Sooo, I implemented the mpl style file scheme so that it kept the spaceKLIP behavior the same while not altering anything else. But that means if someone more advanced (such as yourself) was purposefully overriding the prior settings with your own style configs, that now means you have no way of getting around this in spaceKLIP specific plotting functions other than to manulaly edit the`sk_style.mplstyle` file. 

Perhaps the thing to do is to keep the style file there, but remove any explicit call to it, so that users could decided wether or not to utilize it through their own context manager calls.

**Comment by wbalmer** [comment]
Thanks for the context Jarron. I suppose I selfishly prefer to remove any explicit call or context in spaceKLIP, but that might be a minority opinion, in which case I'm fine to just comment it out on my own dev branches and make do. 

It seems feasible to integrate context manager calls to the spaceKLIP style file into the documentation rather than the module itself, to produce docs with the unified style, but of course that's extra work for folks currently doing documentation development (which I am not clued into).

**Comment by wbalmer** [comment]
Just to report, I still get this issue for matplotlib = 3.8.3.

**Comment by kammerje** [comment]
@JarronL With a fresh installation of spaceKLIP (including the entire Conda environment), I get the following WebbPSF_ext-related error. It appears with both matplotlib==3.9.0 and 3.7.1. It seems related to the issue experienced by @wbalmer.
`OSError: 'webbpsf_ext.wext_style' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)`

**Comment by kammerje** [comment]
Seems like it is not finding the file: `FileNotFoundError: [Errno 2] No such file or directory: 'webbpsf_ext.wext_style'
`

**Comment by JarronL** [comment]
Does this happen when you simply `import webbpsf_ext`? Is there a specific line number where the error is occurring? What type of operating system are you using?

**Comment by AarynnCarter** [comment]
@kammerje @wbalmer are you still having issues with this?

**Comment by wbalmer** [comment]
Yes, just the other day, when doing a fresh pull to push my typo fixes, I verified this issue still plauges me. I have to comment out the affected lines where the style is called. My spaceklip is installed in my home dir, on a Mac M3 system, in a dedicated conda env, via pip in developer mode (pip install -e .).

**Comment by JarronL** [comment]
In an ipython terminal, what happens if you do the following two commands: `plt.style.use('spaceKLIP.sk_style')` and  `plt.style.use('webbpsf_ext.wext_style')`?

**Comment by JarronL** [comment]
An alternative is to copy/paste the two style files, 'sk_style.mplstyle' and 'wext_style.mplstyle' into your `mpl_configdir/stylelib/` directory. To find this, run `matplotlib.get_configdir()`, which is probably something like `~/.matplotlib/`. Then create a directly `~/.matplotlib/stylelib/` and copy the two style files there.

You can then load the custom style sheet with a call to `plt.style.use(sk_style)` and `plt.style.use(wext_style)`. Unfortunately, I don't think that solves your fundamental problem, as it would still require you to replace all lines like `plt.style.context('spaceKLIP.sk_style')` with `plt.style.context('sk_style')`.

I suppose we could perform a try... except... to check the validity of these style files and use the "default" if it they don't exist.

Can you also check what happens for `print(plt.style.available)` and try to load one of them via `plt.style.use()`, or `plt.style.use('default')`?

**Comment by wbalmer** [comment]
> In an ipython terminal, what happens if you do the following two commands: `plt.style.use('spaceKLIP.sk_style')` and `plt.style.use('webbpsf_ext.wext_style')`?

In an interactive python session, I get the following error:

```
(sklipbase) wbalmer@sonofexowill ~ % python
Python 3.11.11 (main, Dec 11 2024, 10:25:04) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spaceKLIP
>>> import matplotlib.pyplot as plt
>>> plt.style.use('spaceKLIP.sk_style')
Traceback (most recent call last):
  File "/Users/wbalmer/miniconda3/envs/sklipbase/lib/python3.11/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wbalmer/miniconda3/envs/sklipbase/lib/python3.11/site-packages/matplotlib/__init__.py", line 870, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/wbalmer/miniconda3/envs/sklipbase/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/wbalmer/miniconda3/envs/sklipbase/lib/python3.11/site-packages/matplotlib/__init__.py", line 847, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'spaceKLIP.sk_style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wbalmer/miniconda3/envs/sklipbase/lib/python3.11/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'spaceKLIP.sk_style' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
```

**Comment by wbalmer** [comment]
> Can you also check what happens for `print(plt.style.available)` and try to load one of them via `plt.style.use()`, or `plt.style.use('default')`?

```
>>> print(plt.style.available)
['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']
>>> plt.style.use('balmer.mplstyle')
```

My problem has never been with matplotlib style files, I actually have my own personal style file that I prefer to initialize in most of the notebooks I use. The bug occurs both in ipython and jupyter notebooks for me on the latest v2.2

**Comment by wbalmer** [comment]
I'm totally fine being outvoted on this point, I'll keep commenting out the lines when I pull new commits, but...

In a broader sense, this is a problem indicates to me that perhaps the style file should not be baked directly into essential spaceklip data reduction classes and analysis via the context wrappers. I think within the plotting module (which I don't use in my own workflow) it is perfectly fine to have a distinct style that is called, but across the package I believe there should be a separate, explicit call by the user for these styles. Perhaps the spaceklip style can be recommended by the documentation (e.g. every tutorial notebook includes a `plt.style.use(sk_style)` call in its top cells). The fact is, even if this didn't produce a breaking error for me, I would still be rather put off by spaceklip enforcing its own style file on me at the function context level, since I have my own preferences.

**Comment by JarronL** [comment]
Completely agree. The only reason it's currently hardcoded is because it was initially hardcoded (unintentionally), and I didn't want to "break" existing plots in example notebooks and people's scripts. We can probably figure out a way of changing this that minimizes impact on prior scripts and notebooks.

**Comment by supernova57-github** [comment]
I've found an easy ad hoc solution to this issue (at least it worked for me). I made a copy of `sk_style.mplstyle`, renamed it to `spaceklip.sk_style`, and moved it to the directory I was executing my script from. Hopefully this can be helpful to someone!

**Comment by AarynnCarter** [comment]
This is now resolved as of PR #269  - closing.
